version: '3.1'
services:
    nginx:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${PUBLIC_PORT}:80'

    php:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
